name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.OSVJE_TOKEN }}
          owner: zzzgydi
          base: main
          head: main

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.OSVJE_TOKEN }}
          owner: zzzgydi
          base: test
          head: test
